### ISSUE TITLE
Apply the same approach to standard multi-view hand-eye problems

### ISSUE THREAD

**Issue by freelist** [MobilePerceptionLab/MultiCamCalib#2]
Dear authors,
thanks for the work, it is very impressive and seems useful also in other multi-camera setups.

E.g., we would like to apply the same method to "standard" robot-camera hand-eye problems, when more than one camera is involved. Can you give a short list of steps that you would follow in that case?

In particular, I see that your code is implementing the calibration of non-overlapping camera setups, in which the external Vycon system is required. What if the setup is the following?

- 1 Robot that mounts the calibration board on his end-effector
- N cameras looking at the robot, observing the scene and the chessboard moving in the workspace

I understood that your problem can be easily ported to our setup by taking into account some "modifications" to your implementation, e.g. the GT trajectory in your case is the trajectory of the chessboard in the Vycon reference system, in our this should be the trajectory of the chessboard in the robot reference system, so, your Vycon origin is equivalent to our robot origin, am I right?

Last thing, is there a way to get from your code the position of each camera w.r.t. the vycon system? I understand the result of your implementation is doing the following assumptions:

- camera 1 is the reference
- each camera extrinsics is expressed w.r.t. camera 1

Correct?

Thanks in advance for your help.

**Comment by 1fwang** [comment]
Hi,

Thanks for your messages.

Yes it could be extended to the setup you described, if you replace the Vycon system to your carefully calibrated robot arm., and Vycon origin is equivalent to the robot origin.

Besides, you can definately get the position of each camera w.r.t to the vycon system, and actually it is one of the direct output of the solver.

If anymore questions, feel free to post here or send to my emails: 1fwang927@gmail.com, or you can read our paper:
https://arxiv.org/pdf/2202.00886.pdf

BR,
Yifu
